In [905]:
import numpy as np
from IPython.display import display, clear_output
from ipywidgets import widgets

In [906]:
from ipywidgets import widgets
from IPython.display import display, clear_output

text = widgets.Text()
display(text)
output = widgets.Output()
display(output)

def handle_submit(sender):
    with output:
        clear_output()
        print('\n'.join([text.value] * 40 ))   

text.on_submit(handle_submit)

Text(value='')

Output()

In [907]:
nrows = 6
ncols = 7
board = np.zeros((nrows,ncols),np.int64)
#board  = np.random.randint(1,30,(nrows,ncols))
print(board)

"""
0 = empty
1 = red
2 = blue
"""

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


'\n0 = empty\n1 = red\n2 = blue\n'

In [908]:
def c4w(player, board): #check for win condition
    for row in range(nrows):
        for col in range(ncols):
            #check horizontal
            if col <= 3:
                rh = np.array(board[row,col:(col+4)])
                if (rh == player).all():
                    print("Player "+str(player)+" has won horizontally")
                    print(str(row)+","+str(col))
                    over=1
                    return over
            # #check left horizontal
            # if col >= 4:
            #     lh = np.array(board[row,(col-4):col])
            #     print("lh: "+str(lh))
            #     if (lh == player).all():
            #         board[row,col] = 69
            #         print("Player "+str(player)+" has won lh")
            #         over=1
            #         return over,row,col
            #check up vertical
            if row >=3:
                uv = np.array(board[(row-3):row+1,col])
                if (uv == player).all():
                    print(uv)
                    print("Player "+str(player)+" has won vertically")
                    over=1
                    return over
            # #check down vertical
            # if row <=3:
            #     dv = np.array(board[row:(row+4),col])
            #     if (dv == player).all():
            #         print("Player "+str(player)+" has won dv")
            #         over=1
            #         return over,row,col
            #check up-right diagonal
            if col <=3 and row >=3:
                urd = np.array([board[row,col],board[row-1,col+1],board[row-2,col+2],board[row-3,col+3]])
                if (urd==player).all():
                    print("Player "+str(player)+" has won up-right diagonally")
                    over=1
                    return over
            #check up-left diagonal
            if col >=3 and row >=3:
                uld = np.array([board[row,col],board[row-1,col-1],board[row-2,col-2],board[row-3,col-3]])
                if (uld==player).all():
                    print("Player "+str(player)+" has won up-left diagonally")
                    over=1
                    return over
            # #check down-left diagonal
            # if col >=3 and row <=2:
            #     dld = np.array([board[row,col],board[row+1,col-1],board[row+2,col-2],board[row+3,col-3]])
            #     if (dld==player).all():
            #         print("Player "+str(player)+" has won dld")
            #         over=1
            #         return over,row,col
            # #check down-right diagonal
            # if col <=3 and row <=2:
            #     drd = np.array([board[row,col],board[row+1,col+1],board[row+2,col+2],board[row+3,col+3]])
            #     if (drd==player).all():
            #         print("Player "+str(player)+" has won drd")
            #         over=1
            #         return over,row,col

In [909]:
np.where(board[:,:]==0)

(array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3,
        3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5],
       dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
        1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       dtype=int64))

In [910]:
def place(player,board,column,over):
    clear_output#(wait=True)
    over = 0 #this should be the natural game state
    remain = np.where(board[:,column] == 0)
    print(remain[-1])
    if len(remain[-1]) >0:
        board[remain[-1][-1],column] = player
    else:
        print("Try another column") #this indicates that the player needs to try again
    over = c4w(player, board)
    if over ==1: #this means the game is over
        print("Winning spot: "+str((nrows-remain[-1][-1],column))) #these are counting from bottom left. (row starts at 0, column starts at 0)
        return board,over
    if np.size(np.where(board[:,:]==0))==0:
        print("Draw")
    return board,over
over = 0

In [915]:
try:
    board,over = place(player = 1,board=board,column = 0,over=over)
    print(board)
    newboard = board
except:
    print(newboard)
    print("Over")


[0 1 2]
[1 1 1 1]
Player 1 has won uv
Winning spot: (4, 0)
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]]


In [912]:
#"""Up right diagonal"""
# for ii in range(3):
#     newboard = place(player = 1,board=board,column = 6)
# board = place(player = 2,board=board,column = 6)
# for ii in range(2):
#     newboard = place(player = 1,board=board,column = 5)
# board = place(player = 2,board=board,column = 5)
# board = place(player = 1,board=board,column = 4)
# board = place(player = 2,board=board,column = 4)
# board = place(player = 2,board=board,column = 3)

#"""Up left diagonal"""
# for ii in range(3):
#     newboard = place(player = 1,board=board,column = 0)
# board = place(player = 2,board=board,column = 0)
# for ii in range(2):
#     newboard = place(player = 1,board=board,column = 1)
# board = place(player = 2,board=board,column = 1)
# board = place(player = 1,board=board,column = 2)
# board = place(player = 2,board=board,column = 2)
# board = place(player = 2,board=board,column = 3)